# fly.toml app configuration file generated for c18-32-ft-java-angular-backend on 2024-05-21T15:13:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'c18-32-ft-java-angular-backend'
primary_region = 'scl'


[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
