name: Backend testing

on:
  push:
    branches: [ "main", "Back-end" ]
  pull_request: 
    branches: [ "Back-end" ]

env:
  ENVIRONMENT_PLATFORM: qa
  MAIL_KEY: ${{ secrets.MAIL_TOKEN }}

concurrency:
  group: ci-${{ github.ref }}-group
  cancel-in-progress: true

jobs:
  test:
    name: Backend tests runner
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./c18-32-ft-java-angular
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
