name: Front-end test
on:
  push:
    branches: [ "main", "Front-end" ]
  pull_request:
    branches: [ "Front-end" ]
jobs:
  Test-Frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Front-end
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test
